// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvBFmoNqYSU9ffvou30GveTkxgJynv5FM',
    appId: '1:283666006110:web:ddc83e2ff9e48fb251f4cf',
    messagingSenderId: '283666006110',
    projectId: 'cvsync-2c3a8',
    authDomain: 'cvsync-2c3a8.firebaseapp.com',
    storageBucket: 'cvsync-2c3a8.firebasestorage.app',
    measurementId: 'G-GJXCNXWGW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmPS-RCOIQBHDehk4Zy7pSw6ViVApKlE4',
    appId: '1:283666006110:android:75f72ff694ca280851f4cf',
    messagingSenderId: '283666006110',
    projectId: 'cvsync-2c3a8',
    storageBucket: 'cvsync-2c3a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjwo6Wf5cyV--7ktjFbxV4CrNdkleKXH0',
    appId: '1:283666006110:ios:e6cf7f03a278e73a51f4cf',
    messagingSenderId: '283666006110',
    projectId: 'cvsync-2c3a8',
    storageBucket: 'cvsync-2c3a8.firebasestorage.app',
    iosBundleId: 'com.example.testCv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjwo6Wf5cyV--7ktjFbxV4CrNdkleKXH0',
    appId: '1:283666006110:ios:e6cf7f03a278e73a51f4cf',
    messagingSenderId: '283666006110',
    projectId: 'cvsync-2c3a8',
    storageBucket: 'cvsync-2c3a8.firebasestorage.app',
    iosBundleId: 'com.example.testCv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvBFmoNqYSU9ffvou30GveTkxgJynv5FM',
    appId: '1:283666006110:web:28e0a9d5e5159f9b51f4cf',
    messagingSenderId: '283666006110',
    projectId: 'cvsync-2c3a8',
    authDomain: 'cvsync-2c3a8.firebaseapp.com',
    storageBucket: 'cvsync-2c3a8.firebasestorage.app',
    measurementId: 'G-CEVHQLRRX1',
  );
}
